[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "common"
publish = false
version = "0.0.0"

[dependencies]
panic-never = "0.1.0"
ufmt = { path = ".." }
ufmt-utils = { path = "../utils" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[workspace]